project:
  type: website
  render:
    - README.md
    - CONTRIBUTING.md
    - LICENSE

website:
  title: "fin-Health"
  navbar:
    title-href: README.md
    left:
      - text: "Contributing"
        href: CONTRIBUTING.md
      - text: "License"
        href: LICENSE

format:
  html:
    theme:
      - cosmos
    toc: true
